### ISSUE TITLE
[OSS] Gatsby 4 upgrade

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#870]
Relates to: 

- https://github.com/newrelic/developer-website/issues/1821
- https://github.com/newrelic/docs-website/pull/5360/files

### Acceptance Criteria 

- [x] Upgrade site to Gatsby 4 (Locally)
- [x] review and fix all the fun errors and assess issues
- [x] once we have slack support with Gatsby discuss our approach
- [ ] determine how to use `createNodeField` correctly so project data renders on preview builds see [PR for approach](https://github.com/newrelic/opensource-website/pull/900)
- [ ] consider aliasing `projectType` field back to it's original location OR update all queries for the new location of project type.

**Comment by jpvajda** [comment]
I've taken this on. 🤠

**Comment by jpvajda** [comment]
all the errrorszzz

```
 ERROR #11321  PLUGIN

"gatsby-source-github-api" threw an error while running the sourceNodes lifecycle:

token is undefined
```

```
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "githubData" on type "Query".

If you don't expect "githubData" to exist on the type "Query" it is most likely a typo.
However, if you expect "githubData" to exist there are a couple of solutions to common problems:

```

```
 ERROR 

Warning: Invalid DOM property `charset`. Did you mean `charSet`?
    at script
    at OneTrust (/Users/jvajda/Documents/Github/DevEn/opensource-website/.cache/page-ssr/routes/render-page.js:6162:3)
    at head
    at html
    at HTML (/Users/jvajda/Documents/Github/DevEn/opensource-website/.cache/page-ssr/routes/render-page.js:4422:76)
```

**Comment by jpvajda** [comment]
I resolved all of those errors and have a new one. I wonder if our gatsby-build-newrelic needs changes to support gatsby 4? 🤔 

```
 ERROR 

There was a problem loading plugin "gatsby-build-newrelic". Perhaps you need to install its package?
Use --verbose to see actual error.
```

**Comment by jpvajda** [comment]
fixed that one, and good ol' sharp is making itself known

```
 Error: Something went wrong installing the "sharp" module
  Cannot find module '../build/Release/sharp-darwin-x64.node'
  Require stack:
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/sharp/lib/sharp.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/sharp/lib/constructor.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/sharp/lib/index.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/@newrelic/gatsby-theme-newrelic/node_modules/gatsby-plugin-sharp/safe-sharp.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/@newrelic/gatsby-theme-newrelic/node_modules/gatsby-plugin-sharp/index.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/@newrelic/gatsby-theme-newrelic/node_modules/gatsby-transformer-sharp/customize-schema.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/@newrelic/gatsby-theme-newrelic/node_modules/gatsby-transformer-sharp/gatsby-node.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/bootstrap/load-config-and-plugins.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/services/initialize.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/services/index.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/state-machines/develop/services.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/state-machines/develop/index.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/node_modules/gatsby/dist/commands/develop-process.js
  - /Users/jvajda/Documents/Github/DevEn/opensource-website/.cache/tmp-66100-50MhyA5mbREH
  Possible solutions:
  - Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
  - Install for the current runtime: "npm install --platform=darwin --arch=x64 sharp"
  - Consult the installation documentation: https://sharp.pixelplumbing.com/install
  ```

**Comment by jpvajda** [comment]
I've added some additional AC to this ticket in case anyone wants to pick it up @zstix
